In [1]:
import numpy as np

In [2]:
A = np.array([[2,2],[2,2]])
alpha = 0.1
itr = 3
X  = np.array([[1],[1]])
for i in range(itr):
    D = A.dot(X)
    X = X - alpha * D

print(X)

[[0.216]
 [0.216]]


In [7]:
A = np.array([[2,-3],[-3,6]])
alpha = 0.1
itr = 3
b = np.array([[2],[5]])
X = np.array([[0],[0]])
for i in range(itr):
    D = A.dot(X) + b
    X = X - alpha * D
print(X)

[[-0.836]
 [-0.957]]


In [3]:
A = np.array([[4,-3,1],[2,1,-2],[3,-2,4]])
b = np.array([[10],[5],[12]])

In [4]:
X = np.linalg.inv(A).dot(b)

In [5]:
X

array([[3.14285714],
       [1.28571429],
       [1.28571429]])

In [4]:
A = np.array([[2,-1,1],[3,2,-1],[-1,4,-2]])
b = np.array([[2],[4],[9]])

In [5]:
X = np.linalg.inv(A).dot(b)

In [6]:
X

array([[-0.14285714],
       [ 6.71428571],
       [ 9.        ]])